# Generated by Django 2.2.1 on 2019-06-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='unknown', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(default='unknown', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('userid', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True)),
                ('location', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('location_contact', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='unknown', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(default='unknown', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_inv', to='invs.Inv')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ipaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='unknown', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(default='unknown', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('hosts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipaddress_hosts', to='assets.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='unknown', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(default='unknown', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('hosts', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostname_hosts', to='assets.Host')),
            ],
        ),
    ]
