# Generated by Django 2.2.1 on 2019-06-03 19:18

import configuration.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateversion', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='unknown', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(default='unknown', max_length=20)),
                ('description', tinymce.models.HTMLField()),
                ('fileName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fileRef', models.FileField(blank=True, null=True, upload_to=configuration.models.upload_to_updates)),
                ('filecreated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
