# Generated by Django 2.2.1 on 2019-06-03 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvAttackvector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='InvCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
                ('reporting_timeframe', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InvPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='InvPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='InvSeverity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='InvStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Inv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invid', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('description_html', models.TextField(blank=True, default='')),
                ('summary', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('invduration', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='unknown', max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(default='unknown', max_length=20)),
                ('attackvector', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_attackvector', to='invs.InvAttackvector')),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_category', to='invs.InvCategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_parent', to='invs.Inv')),
                ('phase', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_phase', to='invs.InvPhase')),
                ('priority', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_priority', to='invs.InvPriority')),
                ('severity', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_severity', to='invs.InvSeverity')),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_status', to='invs.InvStatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
